backend:
  name: git-gateway
# This line should *not* be indented
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "My Angle", name: "myangle", widget: "markdown", required: false}
      - {label: "Tags", name: "tags", widget: "string", required: false}

